#!/usr/bin/env sh
# sudo √iso2usb distro.iso /dev/sdX

# tab complete
file="$1.iso";
file="$1";

# gnome-disks
device="/dev/sd$2";
device="$2";

# kitty >whiskers< nom 🙀🙀 sink!
cat > "$device" < "$file" && sync;

# esc(ape)
exit;
